language: go
go:
  - '1.10'
before_install:
  - sudo apt-get install jq
  - chmod +x gen_aws_creds.sh
  - ./gen_aws_creds.sh
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - chmod +x $GOPATH/bin/dep
  - mkdir dist
install:
  - dep ensure
script:
  - go test -race ./...
  - go build -o ncfsc-events
after_success:
  - zip dist/ncfsc-events.zip ncfsc-events
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: "code-drops"
  local-dir: dist
  acl: private
  on:
    branch: release
after_deploy:
  - chmod +x cloudformation.sh
  - ./cloudformation.sh
env:
  global:
  - secure: AlPwnbFECKBPepby+eg+FtHDXw55v9wWXwwh/ttmxGjcqOkNhDc/H6k+EAPFeA0ZQF591I0aoU/9uHWHPXCiHdnXddheaH4zMY0f2Gjb7Q7yyh8c6Mv4tWfAWDQMF/BlQVZpP/veR2BoFzAtO2jtjGHXrPJJgnUxxd9QtPyioWxZMeAp1jSwm5hxt+z8Or9QM/Li+1H+PpnuhPaO4XXCbEEOm+w6DFKyZ8oIJBxwLbWwhVt4hYXmjh/5XqeZ1WHtlFdhESwL67P5O+bZLJTiMA3ETcAukbZ+VJqQkAs2R18wI1s5LmscS0ntqKqj3jEs4dISHCcbEsVVg0C3lFj8Fl/Hh7TZNH4KJAG2D50pNjIZvMYYnQzATGLrnWs3uoyUQPGGniyasuvoLJuBNtO5VeMCsjNvTr40bMbR0v33TdavfOG0W4C3XSnL4VEQ6ctlcPT7Nf/53DPHx1jHBtKcsgruPZcLFFuZ2+elXJr73SQk05WlKyEFIf7Bj+gRK64My0//3LHLebrnLIBsbT47bLGIUk4eRKXALMxTNwQKitAig1C+wJOUfOUNJWoWHYSVt5uUseC1eyv4RVH4OExS258hcydvmsKThsio6BVVThP+2bbcd5arcmh2EeGrGtMFG0TYtMkmzj7NKt9gCDfifyQb/3wvUjpIXA7pbcqJTj0=
  - secure: UdtdiouAEmmvpXxupWs6rehzh1ROGkernOV7qnae4iKPk3+bz+16Ql5Y1y4kTbfsXqWEWWvBEZsj+8eMw33+zyY+Z1J2ko2e/r4ZDBrgpqS2U5YWXlv59kQpPCrtstREcfu02sHVaaAqtJJeZVg1uVflU6AaN3f351QjLnb2pt3RegZGzqavQtMJKFTcmdK4zrfaD/BYzHdG2gBhbvSUriGvIAVY6fVuwuyZXP8ziVBxjMHXIIMBDOlG4FYH9nEzpOL/BBTGir8gc0+2jF9Lnt2eGA5g667tXENNUDwz6d1aiSvOh9IW0LdVAgCrxYOJuSoVtDUvM+ZmrvH7tQqhtJlTm60feYiiUrEIvA1yhtGQyjzegSnBelpLIC+MVwhMyRgUTT3lz0HtVlb2/3lQ6Xae8z7UYx4MTlDpDP57PCkrrji6I86KGgqSi9PnGJUTTZ/yu9eLyQ+4GMbzwLqy2g25IqxJuHZNBmr3CZernOl/yMXj2ptPLiHaxawcGwq9pobxXPuKDoijIruzaA4RRfCba+JtJyQ5gIqRdHO6Yf+HOkdYykmnPzvA3BG3/7y039Y0pRtOo0aeSbVm3h6Y/C3bfI23Vsr4IsB8k0c8CLH+XeHSJAvzaarJxyUWOEvqOoWP/rnmdCOHlsx9vNoS/80Z0XBfGk8/YpI4OODHsdY=
