version: 0.2

phases:
  install:
    commands:
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - cd ${CODEBUILD_SRC_DIR}; dep ensure
  build:
    commands:
      - go test ./...
      - go build -o ncfsc-events
      - zip ncfsc-events.zip ncfsc-events
  post_build:
    commands:
      - aws cloudformation package --template-file template.json --output-template-file serverless.json --s3-bucket codepipeline-us-east-1-904718901445
artifacts:
  files:
    - serverless.json