version: 0.2

phases:
   install:
     commands:
       - go get github.com/aws/aws-lambda-go/lambda
   build:
     commands:
      - go test ./...
      - go build -o ncfsc-events
      - zip ncfsc-events.zip ncfsc-events
   post_build:
     commands:
      - aws cloudformation package --template-file template.json --output-template-file serverless.json --s3-bucket $BUILD_OUTPUT_BUCKET
 artifacts:
   files:
     - serverless.json